include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    deprecated_member_use: error
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    unnecessary_getters_setters: error
    unnecessary_null_comparison: error
    unnecessary_this: error
    unused_element: error
    unused_import: error
    unused_local_variable: error
    dead_code: error

  language:
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_unused_constructor_parameters: true
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: true
    library_private_types_in_public_api: true
    no_leading_underscores_for_library_prefixes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    require_trailing_commas: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_rethrow_when_possible: true
    use_super_parameters: true

    avoid_build_context_in_providers: true
    avoid_escaping_inner_quotes: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_const_literals_to_create_immutables: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_string_buffers: true
    use_text_style_helper_methods: true
